name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: houqiuhao/vuepressBlog@main
      env:
        ACCESS_TOKEN: ${{ secrets.HAMMER }}
        TARGET_REPO: houqiuhao/vuepressBolg
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm && npm run build
        BUILD_DIR: docs/.vuepress/dist
        # CNAME: https://www.xxx.com